export enum BlockTypesConstant {
    TYPE_FLOW_CONTAINER = "TYPE_FLOW_CONTAINER",
    TYPE_TEXT_SUB_ITEM = "TYPE_TEXT_SUB_ITEM",
    TYPE_MESSAGE_TEXT = "TYPE_MESSAGE_TEXT",
    TYPE_WELCOME = "TYPE_WELCOME",
}